apiVersion: v1
kind: Pod
metadata:
  name: test-container
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  containers:
  - name: test-container
    image: tomcat
    imagePullPolicy: IfNotPresent
